<?php
	$title="Disclaimer";
	include("head.php");
?>

<body>
<div id="wrapper">
<!--Floating Social Icon-->
<?php include("floating_social_icons.php")?>
<!--Fullpage Contact Form-->
<?php include("fullpage_contact_form.php")?>
<!--Header Top-->
<?php include("header_top.php")?>

<section style="margin-top: 7%;">
	<div class="col-lg-12 col-md-12 col-sm-12 col-12 innerpage_breadcrumb_section">
		<ul class="list-unstyled d-flex d-row ml-auto breadcrumb_list">
			<li><a id="breadcrumb_name" href="index.php">Home <span class=" pr-1"> / </span> </a></li>
			<li class="breadcrumb-active">Disclaimer</li>
		</ul>
	</div>
</section>	
<section>
	<div class="col-lg-12 col-md-12 col-sm-12 col-12" id="services_sub_inner_landing_page_section_2">
		<p></p>
		<div class="row mx-0">
			<div class="col-lg-12 col-md-12 col-sm-12 col-12" id="services_sub_inner_landing_page_section_2_left">
				<section>
					<div class="container-fluid px-0" id="about_us_landing_page_section_1">
						<div class="col-lg-12 col-md-12 col-sm-12 col-12" id="" >
							<div class="row mx-0">
								<div class="col-lg-12 col-md-8 col-sm-8 col-12" id="about_us_landing_page_section_1_left">
									<h2 class="about_us_landing_page_section_1_title pt-0">Disclaimer </h2>
									<p>We, MVG Digital Consulting Private Limited, a private limited company having its registered office at “63-D,Shankaran Avenue, Radhakrishnan street, Velachery,Chennai-600042, INDIA”, hereinafter referred to as the “Company (where such expression shall, unless repugnant to the context thereof, be deemed to include its respective legal heirs, representatives, administrators, permitted successors and assigns).</p>

									<p>The creator of this Disclaimer Policy ensures a steady commitment to Your liabilities concerning the usage of the platform “www.imayatech.in” or any other platforms that are operated or connected to the primary platform of the Company (hereinafter referred to as the “Platform”).</p>

									<p>THE COMPANY WILL NOT BE RESPONSIBLE FOR ANY DAMAGE SUFFERED BY USERS REGARDLESS OF IT BEING AN INDIVIDUAL, COMPANY OR A MENTOR OR A VOLUNTEER LISTED ON THE PLATFORM FROM USE OF THIS PLATFORM. THIS INCLUDES BUT IS NOT LIMITED TO, LOSS OF REVENUE/DATA RESULTING FROM DELAYS, NON-DELIVERIES, MISSED DELIVERIES, OR SERVICE INTERRUPTIONS, MENTOR UNAVAILABILITY AS MAY OCCUR BECAUSE OF ANY ACT/OMISSION OF PARTIES. THIS DISCLAIMER OF LIABILITY ALSO APPLIES TO ANY DAMAGES OR INJURY CAUSED BY ANY FAILURE OF PERFORMANCE, ERROR, OMISSION, INTERRUPTION, DELETION, DEFECT, DELAY IN OPERATION OR TRANSMISSION, COMPUTER VIRUS, COMMUNICATION LINE FAILURE, THEFT OR DESTRUCTION OR UNAUTHORIZED ACCESS TO, ALTERATION OF, OR USE OF RECORD, WHETHER FOR BREACH OF CONTRACT, TORTUOUS BEHAVIOUR, NEGLIGENCE, OR UNDER ANY OTHER CAUSE OF ACTION.</p>

									<p>THE COMPANY ALSO MAKES IT CLEAR THAT IT SHALL NOT BE HELD LIABLE FOR ANY DAMAGE/HURT/INCONVENIENCE CAUSED TO THE MENTOR OR VOLUNTEER OR THE COMPANY THROUGH THE COURSE OF PROVIDING THEIR AVAILABILITY THROUGH THE PLATFORM.  THE COMPANY MAKES NO REPRESENTATIONS OR WARRANTIES AS TO THE CONDUCT OF THE INDIVIDUAL USER. THE COMPANY TAKES NO RESPONSIBILITY FOR ANY CONTENT THAT MENTORS SEND OR RECEIVE FROM THE INDIVIDUAL USER THROUGH THE PLATFORM. ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH USE OF THE PLATFORM IS ACCESSED AT THEIR DISCRETION AND RISK.</p>

									<p>THE SERVICES ON THE PLATFORM ARE INTENDED TO BE SUBJECT TO AVAILABILITY, WITHOUT ANY PROMISES OR GUARANTEES ON THE SAME BY THE COMPANY, AND WHILE CERTAIN INFORMATION AVAILABLE ON THE PLATFORM IS THE PROPERTY OF THE COMPANY AND THE COMPANY ENDEAVOURS TO KEEP THE SAID INFORMATION UPDATED AND ACCURATE, THE COMPANY SHALL NOT MAKE REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, ABOUT THE COMPLETENESS, ACCURACY, RELIABILITY, SUITABILITY OR AVAILABILITY WITH RESPECT TO THE PLATFORM OR THE INFORMATION, CUSTOMERS, SERVICES, OR RELATED GRAPHICS CONTAINED ON THE PLATFORM FOR ANY PURPOSE. ANY RELIANCE YOU PLACE ON SUCH INFORMATION IS THEREFORE STRICTLY AT YOUR OWN RISK.</p>

									<p>THE SERVICES ON THE PLATFORM ARE BASED ON THE INFORMATION THAT IS GIVEN BY THE USER AND THE CORRECTNESS OR AUTHENTICITY OF THE SAME IS ASSURED BY THE USERS, THE USERS CANNOT HOLD THE PLATFORM ACCOUNTABLE FOR THE MISTAKES CAUSED BY ANY ERROR IN THE INFORMATION</p>

									<p>ANY AND OR ALL THE INTELLECTUAL PROPERTY ON THE COMPANY PLATFORM MAY HAVE BEEN TRADEMARKED OR COPYRIGHTED BY THE COMPANY AND OR ANY OTHER SUCH PERSON AND ANY USE, MISUSE OR MANIPULATIONS THAT MAY BE IN RELATION TO THE INTELLECTUAL PROPERTY SHALL BE THE RESPONSIBILITY OF THE COMPANY. HOWEVER, WHEN BROUGHT TO THE NOTICE OF THE COMPANY, THERE SHALL BE IMMEDIATE LEGAL ACTION TAKEN.</p>

									<p>THE COMPANY BEARS NO RESPONSIBILITY WHATSOEVER FOR ANY CONSEQUENCES ARISING FROM THE USE OF THE SAID SERVICES. THE USE OF THE PLATFORM IS THE SOLE RESPONSIBILITY OF THE USERS (OR LEGALLY AUTHORISED PERSON ON BEHALF OF THE USERS AS THE CASE MAY BE), AND IN CASE OF ANY NEGLIGENCE ON THE PART OF THE USERS IN ACTING ON THE SAME SHALL NOT BE CONSTRUED AS IMPOSING ANY LIABILITY, DIRECT OR INDIRECT, ON THE COMPANY/PLATFORM.</p>

									<p>THROUGH THIS PLATFORM, USER MAY ABLE TO LINK TO OTHER PLATFORMS WHICH ARE NOT UNDER THE CONTROL OF THE COMPANY. THE COMPANY HAS NO CONTROL OVER NATURE, CONTENT AND AVAILABILITY OF THOSE SITES. THE INCLUSION OF ANY LINKS DOES NOT NECESSARILY IMPLY A RECOMMENDATION OR ENDORSE THE VIEWS EXPRESSED WITHIN THEM. EVERY EFFORT IS MADE TO KEEP THE PLATFORM UP AND RUNNING SMOOTHLY. HOWEVER, THE COMPANY TAKES NO RESPONSIBILITY FOR, AND WILL NOT BE LIABLE FOR, THE PLATFORM BEING TEMPORARILY UNAVAILABLE DUE TO TECHNICAL ISSUES BEYOND OUR CONTROL.</p>

									<p>THE USER UNDERSTANDS AND AGREES THAT ANY MATERIAL OR DATA DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE PLATFORM IS DONE ENTIRELY AT HIS/HER OWN DISCRETION AND RISK AND HE/SHE WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO HIS/HER COMPUTER SYSTEMS OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF SUCH MATERIAL OR DATA. COMPANY IS NOT RESPONSIBLE FOR ANY TYPOGRAPHICAL ERROR. PLATFORM ACCEPTS NO LIABILITY FOR ANY ERRORS OR OMISSIONS, CONCERNING ANY INFORMATION PROVIDED TO YOU WHETHER ON BEHALF OF ITSELF OR THIRD PARTIES.</p>




								</div>
								
							</div>
						</div>
					</div>
				</section>
			</div>
		</div>
	</div>
<?php include("footer.php")?>
<script>
	window.onscroll = function() {myFunction()};

	var navbar = document.getElementById("navbar-section");
	var sticky = navbar.offsetTop;

	function myFunction() 
	{
		if (window.pageYOffset >= sticky) 
		{
			navbar.classList.add("sticky")
		}
		else 
		{
			navbar.classList.remove("sticky");
		}
	}
</script>
		