<?php
	$title="Terms & Conditions ";
	include("head.php");
?>

<body>
<div id="wrapper">
<!--Floating Social Icon-->
<?php include("floating_social_icons.php")?>
<!--Fullpage Contact Form-->
<?php include("fullpage_contact_form.php")?>
<!--Header Top-->
<?php include("header_top.php")?>

<section style="margin-top: 7%;">
	<div class="col-lg-12 col-md-12 col-sm-12 col-12 innerpage_breadcrumb_section">
		<ul class="list-unstyled d-flex d-row ml-auto breadcrumb_list">
			<li><a id="breadcrumb_name" href="index.php">Home <span class=" pr-1"> / </span> </a></li>
			<li class="breadcrumb-active">Terms & Conditions </li>
		</ul>
	</div>
</section>	
<section>
	<div class="col-lg-12 col-md-12 col-sm-12 col-12" id="services_sub_inner_landing_page_section_2">
		<p></p>
		<div class="row mx-0">
			<div class="col-lg-12 col-md-12 col-sm-12 col-12" id="services_sub_inner_landing_page_section_2_left">
				<section>
					<div class="container-fluid px-0" id="about_us_landing_page_section_1">
						<div class="col-lg-12 col-md-12 col-sm-12 col-12" id="" >
							<div class="row mx-0">
								<div class="col-lg-12 col-md-8 col-sm-8 col-12" id="about_us_landing_page_section_1_left">
									<h2 class="about_us_landing_page_section_1_title pt-0">Terms & Conditions  </h2>
									<p>We, MVG Digital Consulting Private Limited, a private limited company having its registered office at “63-D,Shankaran Avenue, Radhakrishnan street, Velachery,Chennai-600042, INDIA”, hereinafter referred to as the “Company (where such expression shall, unless repugnant to the context thereof, be deemed to include its respective legal heirs, representatives, administrators, permitted successors and assigns).</p>

									<p>This legal agreement is an electronic record in terms of Indian Information Technology Act, 2000 and rules there under as applicable and the amended provisions about electronic records in various statutes as amended by the Indian Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>

									<p>This legal document is published in accordance with the provisions of Rule 3 (1) of the Indian Information Technology (Intermediaries guidelines) Rules, 2011 and Rule 4 of the Information Technology (Reasonable security practices and procedures and sensitive personal data or information) Rules, 2011 of Information Technology Act, 2000 amended through Information Technology Amendment Act, 2008 that require publishing the Terms of Services and practices for access or usage of the Website.</p>

									<p>The Company ensures steady commitment to your usage of the Platform and privacy concerning the protection of your invaluable information. This document contains information about the Website “www.imayatech.in” and the other associated domains owned and purchased by the Company (hereinafter referred to as the “Platform”).</p>

									<p>For these Terms of Use (“Terms”), wherever the context so requires,<br>

									“We”, “Our”, and “Us” shall mean and refer to the Domain and/or the Company, as the context so requires.<br>
									“You”, “Your”, “Yourself”, “User”, shall mean and refer to a natural and legal individual user, recruiter company, mentor, volunteers, prospective Employers or any other person who use the Platform and who is competent to enter into binding contracts, as per Indian laws.<br>
									“Third Parties” refer to any Platform, Company or individual apart from the User, and the creator of this Platform. It shall include such payment gateways as partnered by the Company.<br>
									The term “Platform” refers to the Website/Domain created by the Company which provides the Client to avail services of the Company through the use of the Platform.<br>
									The headings of each section in these Terms are only to organize the various provisions under these Terms in an orderly manner and shall not be used by either Party to interpret the provisions contained herein in any manner. Further, it is specifically agreed to by the Parties that the headings shall have no legal or contractual value.<br>
									The use of this Platform by the Users is solely governed by these Terms as well as the Privacy Policy and other policies as listed on the Platform, and any modifications or amendments made thereto by the Company, from time to time, at its sole discretion. If you continue to access and use this Platform, you are agreeing to comply with and be bound by the following Terms and Conditions of Use and Our Privacy Policy. The User expressly agrees and acknowledges that these Terms and Policy are co-terminus in nature and that expiry/termination of either one will lead to the termination of the other.<br>
									The User unequivocally agrees that these Terms and the aforementioned Policy constitute a legally binding agreement between the User and the Company, and that the User shall be subject to the rules, guidelines, policies, terms, and conditions applicable to any product or service that is provided by the Platform, and that the same shall be deemed to be incorporated into these Terms, and shall be treated as part and parcel of the same. The User acknowledges and agrees that no signature or express act is required to make these Terms and the Policy binding on the User and that the User’s act of visiting any part of the Platform constitutes the User’s full and final acceptance of these Terms and the aforementioned Policy.<br>
									The Company reserves the sole and exclusive right to amend or modify these Terms without any prior permission or intimation to the User, and the User expressly agrees that any such amendments or modifications shall come into effect immediately. The User must periodically check the terms and stay updated on its requirements. If the User continues to use the Platform following such a change, the User will be deemed to have consented to any amendments/modifications made to the Terms. In so far as the User complies with these Terms, it is granted a personal, non-exclusive, non-transferable, revocable, limited privilege to access and use the Platform and the Services. If the User does not adhere to the changes, User must stop using the Platform at once. Your continued use of the Platform will signify your acceptance of the changed terms.</p>
									
									<h6 class="finally_why_us_title">REQUIREMENTS FOR USE OF THE PLATFORM</h6>

									<p>Use of the Platform requires a compatible device, Internet access, and/or certain software; may require periodic updates; and may be affected by the performance of these factors. High-speed Internet access is strongly recommended for regular use and is required for video; access or cellular data fees may apply. Mobile applications may require iOS 8 or Android 4.1 or later. The latest version of required software is recommended and may be required for certain transactions or features. You agree that meeting these requirements, which may change from time to time, is your responsibility.</p>


									<h6 class="finally_why_us_title">REGISTRATION</h6>

									<p>Registration is mandatory for Users to access any of the features provided by the Platform. 
									Users may be Individuals who are accessing the Platform to learn something or who are interested in teaching on the Platform. </p>
									<p>Individuals shall register on the platform as users by providing at least the following minimum details <br>
									First Name<br>
									Last Name<br>
									Age<br>
									Email Id<br>
									Phone Number<br>
									Pin Code of their residence</p>
									<p>Teachers shall register on the platform by providing at least the following details:<br>
									First Name<br>
									Last Name<br>
									Photo<br>
									Age<br>
									Email ID<br>
									Phone Number<br>
									Bio<br>
									Areas of Expertise <br>
									Availability <br>
									Schedule of Classes</p> 
									<p>Company shall register on the platform by providing at least the following details:
									Name<br>
									Registered Address<br>
									Contact Details<br>
									Industry<br>
									Number of Teachers </p>
									<p>Further, at any time during the use of this Platform, including but not limited to the time of registration, Users are solely responsible for protecting the confidentiality of their username and password, and any activity under the account shall be deemed to have been done by Users.
									The Individuals registering on the platform shall be charged in accordance with the fee structure, to avail the membership respectively, provided by the Platform.</p>

									<h6 class="finally_why_us_title">PLATFORM OVERVIEW</h6>

									<p>Imaya Tech is a brand of MVG Digital Consulting Private Limited, which is a company registered under the provisions of the Companies Act 2013 and has its registered office situated at Chennai, India. The Platform is operated by the Company to bring teachers who are teaching various skills, arts, etc… with students who are looking at learning these skills, arts, etc.</p>

									<p>The Company through the platform allows registered teachers to create, publish, collect and teach live programs, skills, arts, etc... The Platform allows registered students to then register, connect, pay and learn the said skills from the teacher of the said program, skill, art, etc…  </p>

									<h6 class="finally_why_us_title">ELIGIBILITY</h6>

									<p>The User represents and warrants that they are competent and eligible to enter into legally binding agreements and are of majority age as per the local laws of the Country the User is operating out of and that they have the requisite authority to bind themselves to these Terms under the Law.</p>

									<h6 class="finally_why_us_title">CONTENT</h6>
									<p>All text, graphics, User interfaces, visual interfaces, photographs, trademarks, logos, brand names, descriptions, sounds, music and artwork (collectively, ‘Content’), is generated by Platform and the Platform has control over it and assures a reasonable quality, the accuracy, integrity or genuineness of features available for the User on the Platform.</p>

									<p>All the Content displayed on the Platform is subject to copyright and shall not be reused by any party (or a third party) without the prior written consent of the Company and the copyright owner.</p>

									<p>The Users are solely responsible for the integrity, authenticity, quality and genuineness of the feedback and comments by Users can be made via the Platform, the Platform bears no liability whatsoever for any feedback or comments made by the Users or made in respect of any of the content on the Platform.  Further, the Platform reserves its right to suspend the account of any User for an indefinite period to be decided at the discretion of the Platform or to terminate the account of any User who is found to have created or shared or submitted any Content or part thereof that is found to be untrue/inaccurate/misleading or offensive/vulgar. The User shall be solely responsible for making good any financial or legal losses incurred through the creation/sharing/submission of Content or part thereof that is deemed to be untrue/inaccurate/misleading.</p>

									<p>The Users have a personal, non-exclusive, non-transferable, revocable, limited privilege to access the Content on the Platform. Users shall not copy, adapt, and modify any content without written permission of the Company.</p>

									<h6 class="finally_why_us_title">TERM</h6>
									<p>
									These Terms shall continue to form a valid and binding contract between the Parties and shall continue to be in full force and effect until the User continues to access and use the Platform.
									The Users may terminate their use of the Platform at any time.
									The Company may terminate these Terms and close a User’s account at any time without notice and/or suspend or terminate a User’s access to the Platform at any time and for any reason, if any discrepancy or legal issue arises.
									Such suspension or termination shall not limit our right to take any other action against you that the Company considers appropriate.
									It is also hereby declared that the Company may discontinue the Services and Platforms without any prior notice.
									<h6 class="finally_why_us_title">TERMINATION</h6>
									The Company reserves the right, in its sole discretion, to unilaterally terminate the User’s access to the Platform, or any portion thereof, at any time, without notice or cause.
									The Platform also reserves the universal right to deny access to particular users, to any/all of are on its Platform without any prior notice/explanation to protect the interests of the Platform and/or other visitors to the Platform.
									The Platform reserves the right to limit, deny or create different access to the Platform and its features concerning different Users, or to change any of the features or introduce new features without prior notice.
									The User shall continue to be bound by these Terms, and it is expressly agreed to by the Parties that the User shall not have the right to terminate these Terms till the expiry of the same.

									<h6 class="finally_why_us_title">COMMUNICATION</h6>

									By using this Platform and providing his/her identity and contact information to the Company through the Platform, the Users hereby agree and consent to receive calls, e-mails or SMS from the Company and/or any of its representatives at any time.

									Users can report to “support@imayatech.in” if they find any discrepancy concerning Platform or content-related information and the Company will take necessary action after an investigation. The response with resolution (if any issues found) shall be dependent on the time is taken for investigation.
									The User expressly agrees that notwithstanding anything contained hereinabove, he/she may be contacted by the Company or any representatives relating to any services availed by the User on the Platform or anything pursuant thereto and the Users agrees to indemnify the Company from any harassment claims. It is expressly agreed to by the Parties that any information shared by the User with the Company shall be governed by the Privacy Policy.

									<h6 class="finally_why_us_title">PAYMENT CHARGES</h6>

									The Individual Users registering on the platform shall be subjected to charges based on the type of Class, Program, skill course, etc… that they sign up for expressly. The Individual registered for the specific class program and/or skill course shall be subjected to payment, as specified by the Company on the platform to avail such as services. The Individual Users who shall register themselves as users shall be free of cost and their access to the platform shall be limited at the discretion of the Company.

									The Company will not be liable for any credit or debit card fraud. The liability to use a card fraudulently will be on the user and the onus to ‘prove otherwise’ shall be exclusively on the user. To provide a safe and secure Platform Experience and to avail services, the Company regularly monitors transactions for fraudulent activity. In the event of detecting any suspicious activity, the Company reserves the right to cancel all past, pending and future requests without any liability.

									The Company shall disclaim all responsibility and owns no liability to Users for any outcome (incidental, direct, indirect or otherwise) from the use of the Services. The Company, as a merchant, shall be under no liability whatsoever in respect of any loss or damage arising directly or indirectly out of the decline of authorization for any Transaction, on Account of the Cardholder having exceeded the preset limit mutually agreed by us with our acquiring bank from time to time.

									<h6 class="finally_why_us_title">REFUNDS</h6>
									Since the Company is mostly offering in-tangible, irrevocable digital goods via the Platform, the Company does not issue refunds after the sale. Users should make sure they’ve carefully read and understood all the relevant description, documentation and instructions as given in the Platform, before payment of Fees for a given program, skill course or class. Please feel free to drop us an email at support@imayatech.in if you have any queries relating to the same.

									The Company is not responsible for any loss / corruption of data that may occur during the process of streaming / downloading it if you fail to correctly follow the instructions and/ or for reasons not directly attributable to the process/ software used by us for completing the process of making the data available for your streaming / download. The Company is also not responsible for non-completion of the transaction as a result of events beyond our control, such as power cuts, disconnection of internet services by Users’ service provider, use of incompatible third party software by User, refusal of request by the service provider at the time of making electronic payments, etc.
									In cases where the data that has been streamed / downloaded is found to be corrupt or unplayable for any fault of the Website, the Company / Platform would not provide a refund but would instead provide you with a working copy for re-download of the same. 

									In case of paid live stream / webcast of programs, workshops, 

									End users viewing the webcast will need a minimum download speed of 2 MBPS to view the webcast without buffering & delays. User Internet speeds / bandwidth can be verified at speedtest.net or of testmy.net or nperf.com or any other internet speed test website. 
									The Company shall consider a refund only if the event is cancelled by the Teacher or if more than 80% of the event had technical issues (no sound, or poor sound & video quality)
									The Company only makes exceptions on a case by case basis.
									The deadline for making any refund claim is within 7 days after the purchase.

									<h6 class="finally_why_us_title">USER OBLIGATIONS AND FORMAL UNDERTAKINGS AS TO CONDUCT</h6>
									The Users agree and acknowledge that they are a restricted user of this Platform and that they:

									Agree to provide genuine credentials during the process of registration on the Platform. Users agree that they shall not use a fictitious identity to register. The Company is not liable if the User has provided incorrect information.
									Agree to ensure the Name, Email address, Address, Mobile number and any such other information provided during registration is valid at all times and shall keep their information accurate and up-to-date. The User can update their details anytime through accessing their profile on the Platform.
									Agree that they are solely responsible for maintaining the confidentiality of the account password. Users agree to notify the Company through the Platform immediately of any unauthorized use of their account. Company reserves the right to close User’s account at any time for any or no reason.
									Understand and acknowledge that the data submitted is manually entered into the database of the Platform. The User also acknowledges the fact that data so entered into the database is for easy and ready reference, and to streamline their use of the Platform.
									Authorize the Platform to use, store or otherwise process certain personal information and all published Content, responses, locations, comments, reviews and ratings for personalization purposes, marketing and promotional purposes and optimisation of User-related options and Services.
									Understand and agree that, to the fullest extent permissible by law, the Platform/Company and their successors and assigns, or any of their affiliates or their respective officers, directors, employees, agents, licensors, representatives, operational service providers, advertisers or suppliers shall not be liable for any loss or damage, of any kind, direct or indirect, in connection with or arising from the use of the Platform or this terms of use, including, but not limited to, compensatory, consequential, incidental, indirect, special or punitive damages.
									Are bound not to cut, copy, modify, recreate, reverse engineer, distribute, disseminate, post, publish or create derivative works from, transfer, or sell any information or obtained from the Platform. Any such use/limited use of the Platform will only be allowed with the prior express written permission of the Company.
									Agree not to access (or attempt to access) the Platform and/or the materials or Services by any means other than through the interface provided by the Platform. The use of deep-link, robot, spider or other automatic devices, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy or monitor any portion of the Platform or its content, or in any way reproduce or circumvent the navigational structure or presentation of the Platform, materials or any content, or to obtain or attempt to obtain any materials, documents or information through any means not specifically made available through the Platform will lead to suspension or termination of the User’s access to the Platform. The User acknowledges and agrees that by accessing or using the Platform or any of the Services provided therein, it may be exposed to content that it may consider offensive, indecent or otherwise objectionable. The Company disclaims any liabilities arising concerning such offensive content on the Platform.
									Expressly agree and acknowledge that the Content generated by the User and displayed on the Platform is owned by the Company and however the Company is in no way responsible for the content of the same. The User may, however, report any offensive or objectionable content, which the Company may then remove from the Platform, at its sole discretion.
									Expressly consents to follow the terms and conditions, and policies of the Company from whom the Users are utilizing services.
									The User further undertakes not to:

									Engage in any activity that interferes with or disrupts access to the Platform provided therein (or the servers and networks which are connected to the Platform);
									Impersonate any person or entity, or falsely state or otherwise misrepresent his/her affiliation with a person or entity;
									Probe, scan or test the vulnerability of the Platform or any network connected to the Platform, nor breach the security or authentication measures on the Platform or any network connected to the Platform. The User may not reverse look-up, trace or seek to trace any information relating to any other User of, or visitor to, the Platform, or any other viewer of the Platform, including any User account maintained on the Platform not operated/managed by the User, or exploit the Platform or information made available or offered by or through the Platform, in any manner;
									Disrupt or interfere with the security of, or otherwise cause harm to, the Platform, systems resources, accounts, passwords, servers or networks connected to or accessible through the Platform or any affiliated or linked Platforms;
									Use the Platform or any material or content therein for any purpose that is unlawful or prohibited by these Terms, or to solicit the performance of any illegal activity or other activity which infringes the rights of this Platform or any other third party(s);
									Violate any code of conduct or guideline which may apply for or to any particular service offered on the Platform;
									Violate any applicable laws, rules or regulations currently in force within or outside India;
									Violate any portion of these Terms or the Privacy Policy, including but not limited to any applicable additional terms of the Platform contained herein or elsewhere, whether made by amendment, modification, or otherwise;
									Commit any act that causes the Company to lose (in whole or in part) the Services of its Internet Establishment (“ISP“) or in any manner disrupts the Services of the Company/Platform;
									Further:

									The User hereby expressly authorizes the Company/Platform to disclose any information relating to the User in the possession of the Company/Platform to law enforcement or other government officials, as the Company may in its sole discretion, believe necessary or appropriate in connection with the investigation and/or resolution of possible crimes, especially those that involve personal injury and theft/infringement of intellectual property. The User further understands that the Company/Platform might be directed to disclose any information (including the identity of persons providing information or materials on the Platform) as necessary to satisfy any judicial Order, law, regulation or valid governmental request.
									The User agrees to use the services and products provided by the Company, its affiliates, consultants and contracted companies, for lawful purposes only.
									The User agrees not to make any resale of the Company’s products or services. In case of any such instances, the Company reserves all rights to cancel and block the concerned User account (s).
									The User agrees to provide authentic and true information. The Company reserves the right to validate the information and other details provided by the User at any point of time. If upon such User details are found to be false, not to be true (wholly or partly), the Company shall in its sole discretion reject the registration and debar the User from using the Services available on its Website, and/or other affiliated websites without prior intimation whatsoever.
									The User agrees not to post any material on the website that is defamatory, offensive, obscene, indecent, abusive, or needlessly distressful, or advertising any services. More specifically, the User agrees not to host, display, upload, update, publish, modify, transmit, or in any manner share any information that:
									belongs to another person and to which the User has no right to;
									is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libellous, invasive of another’s privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever;
									is in any way harmful to minors;
									infringes any patent, trademark, copyright or other proprietary rights;
									violates any law for the time being in force;
									deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing;
									Abuse, harass, threaten, defame, disillusion, erode, abrogate, demean or otherwise violate the legal rights of others;
									Impersonate any person or entity, or falsely state or otherwise misrepresent User’s affiliation with a person or entity;
									Publish, post, disseminate, any grossly harmful information, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libellous, invasive of another’s privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever; or unlawfully threatening or unlawfully harassing including but not limited to “indecent representation of women” within the generally and universally accepted meaning.
									Threatens the unity, integrity, defence, security or sovereignty, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation.
									<h6 class="finally_why_us_title">SUSPENSION OF USER ACCESS AND ACTIVITY</h6>
									Notwithstanding other legal remedies that may be available, the Platform may in its sole discretion, limit the User’s access and/or activity by immediately removing the User’s access credentials either temporarily or indefinitely, or suspend/terminate the User’s association with the Platform, and/or refuse to the usage of the Platform to the User, without being required to provide the User with notice or cause:

									If the User is in breach of any of these Terms or the Policy;
									If the User has provided wrong, inaccurate, incomplete or incorrect information;
									If the User’s actions may cause any harm, damage or loss to the other Users or the Company, at the sole discretion of the Company.

									<h6 class="finally_why_us_title">INDEMNITY</h6>

									The Users of this Platform agree to indemnify, defend and hold harmless the Company/Platform, and their respective directors, officers, employees and agents (collectively, “Parties”), from and against any losses, liabilities, claims, damages, demands, costs and expenses (including legal fees and disbursements in connection therewith and interest chargeable thereon) asserted against or incurred by us that arise out of, result from, or maybe payable by, any breach or non-performance of any representation, warranty, covenant or agreement made or obligation to be performed according to these terms of use. Further, the User agrees to hold the Company/Platform harmless against any claims made by any third party due to, or arising out of, or in connection with:

									User’s use of the Platform,
									User’s violation of these Terms and Conditions;
									User’s violation of any rights of another;
									User’s alleged improper conduct under these Services;
									User’s conduct in connection with the Platform;
									User agrees to fully cooperate in indemnifying the Company and the Platform at the user’s expense. The user also agrees not to settle with any party without the consent of the Company.

									In no event shall the Company/Platform be liable to compensate the User or any third party for any special, incidental, indirect, consequential or punitive damages whatsoever, including those resulting from loss of use, data or profits, whether or not foreseeable, and whether or not the Company/ Platform had been advised of the possibility of such damages, or based on any theory of liability, including breach of contract or warranty, negligence or other tortuous action, or any other claim arising out of or in connection with the User’s use of or access to the Platform and/or the Services or materials contained therein.

									<h6 class="finally_why_us_title">LIMITATION OF LIABILITY</h6>

									The Founders/ Promoters/ Partners/ Associated people of the Company/Platform are not responsible for any consequences arising out of the following events:
									If the Platform is inoperative/non-responsive due to any connectivity errors associated with the internet connection such as but not limited to slow connectivity, no connectivity, server failure;
									If the User has fed incorrect information or data or for any deletion of data;
									If there is an undue delay or inability to communicate through email;
									If there is any deficiency or defect in the Services managed by Us;
									If there is a failure in the functioning of any other service provided by the Platform.
									The Platform accepts no liability for any errors or omissions, on behalf of itself, or for any damage caused to the User, the User’s belongings, or to any third party, resulting from the use or misuse of the Platform or any service availed of by the User through the Platform. The service and any Content or material displayed on the service is provided without any guarantees, conditions or warranties as to its accuracy, suitability, completeness or reliability. The Platform will not be liable to you for the unavailability or failure of the Platform.
									Users are to comply with all laws applicable to them or their activities, and with all Policies, which are hereby incorporated into this Agreement by reference.
									The Platform expressly excludes any liability for any loss or damage that was not reasonably foreseeable by the Platform and which is incurred by you in connection with the Platform, including loss of profits; and any loss or damage incurred by you as a result of your breach of these terms.
									To the fullest extent permitted by law, the Platform shall not be liable to you or any other party for any loss or damage, regardless of the form of action or basis of any claim. You acknowledge and agree that your sole and exclusive remedy for any dispute with us is to terminate your use of the Platform.

									<h6 class="finally_why_us_title">INTELLECTUAL PROPERTY RIGHTS</h6>

									Unless expressly agreed to in writing, nothing contained herein shall give the User a right to use any of the Platform’s trademarks, service marks, logos, domain names, information, questions, answers, solutions, reports and other distinctive brand features, save according to the provisions of these Terms. All logos, trademarks, brand names, service marks, domain names, including material, designs, and graphics created by and developed by the Platform and other distinctive brand features of the Platform are the property of the Company or the respective copyright or trademark owner. Furthermore, concerning the Platform created by the Company, the Company shall be the exclusive owner of all the designs, graphics and the like, related to the Platform.

									The User may not use any of the intellectual property displayed on the Platform in any manner that is likely to cause confusion among existing or prospective Users of the Platform, or that in any manner disparages or discredits the Company/Platform, to be determined in the sole discretion of the Company.

									<h6 class="finally_why_us_title">DISCLAIMER OF WARRANTIES AND LIABILITIES</h6>

									The User agrees and undertakes that they are accessing the Platform at their sole risk and are that they are using their best and prudent judgment before availing any service listed on the Platform or accessing/using any information displayed thereon.
									The User agrees that any kind of information, resources, activities, recommendations obtained/availed from Platform, written or oral, will not create any warranty and the Platform disclaims all liabilities resulting from these.
									The Company/Platform does not guarantee that the Services contained in the Platform will be uninterrupted or error-free, or that the Platform or its server will be free of viruses or other harmful components, and the User hereby expressly accepts any associated risks involved with the User’s use of the Platform.
									It is further agreed to by the Parties that the contents of this Section shall survive even after the termination or expiry of the Terms and/or Policy.

									<h6 class="finally_why_us_title">FORCE MAJEURE</h6>

									Neither the Company nor the Platform shall be liable for damages for any delay or failure to perform its obligations hereunder if such delay or failure is due to cause beyond its control or without its fault or negligence, due to Force Majeure events including but not limited to acts of war, acts of God, earthquake, riot, fire, festive activities, sabotage, labour shortage or dispute, internet interruption, technical failure, breakage of sea cable, hacking, piracy, cheating, or held illegal or unauthorized.

									<h6 class="finally_why_us_title">DISPUTE RESOLUTION AND JURISDICTION</h6>

									It is expressly agreed to by the Parties hereto that the formation, interpretation and performance of these Terms and any disputes arising therefrom will be resolved through a two-step Alternate Dispute Resolution (“ADR”) mechanism. It is further agreed to by the Parties that the contents of this Section shall survive even after the termination or expiry of the Terms and/or Policy.

									<h6 class="finally_why_us_title">MEDIATION</h6>

									In case of any dispute between the parties, the Parties will attempt to resolve the same amicably amongst themselves, to the mutual satisfaction of all parties. If the Parties are unable to reach such an amicable solution within thirty (30) days of one Party communicating the existence of a dispute to any other Party, the dispute will be resolved by arbitration, as detailed hereinbelow;
									Arbitration: If the Parties are unable to amicably resolve a dispute by mediation, said dispute will be referred to arbitration by a sole arbitrator to be appointed by the Company, and the award passed by such sole arbitrator will be valid and binding on all parties. The Parties shall bear their costs for the proceedings, although the sole arbitrator may, in his/her sole discretion, direct either Party to bear the entire cost of the proceedings. The arbitration shall be conducted in English, and the seat of Arbitration shall be at Chennai, Tamil Nadu.
									The Parties expressly agree that the Terms of Use, Privacy Policy and any other agreements entered into between the Parties are governed by the laws, rules and regulations of India.

									<h6 class="finally_why_us_title">NOTICES</h6>

									Any and all communication relating to any dispute or grievance experienced by the User may be communicated to the Company by the User by emailing to support@imayatech.in.

									<h6 class="finally_why_us_title">MISCELLANEOUS PROVISIONS</h6>
									Entire Agreement: These Terms, read with the Policy, form the complete and final contract between the User and the Company with respect to the subject matter hereof and supersedes all other communications, representations and agreements (whether oral, written or otherwise) relating thereto.
									Waiver: The failure of either Party at any time to require performance of any provision of these Terms shall in no manner affect such Party’s right at a later time to enforce the same. No waiver by either party of any breach of these Terms, whether by conduct or otherwise, in any one or more instances, shall be deemed to be or construed as a further or continuing waiver of any such breach, or a waiver of any other breach of these Terms.
									Severability: If any provision/clause of these Terms is held to be invalid, illegal or unenforceable by any court or authority of competent jurisdiction, the validity, legality and enforceability of the remaining provisions/clauses of these Terms shall in no way be affected or impaired thereby, and each such provision/clause of these Terms shall be valid and enforceable to the fullest extent permitted by law. In such case, these Terms shall be reformed to the minimum extent necessary to correct any invalidity, illegality or unenforceability, while preserving to the maximum extent the original rights, intentions and commercial expectations of the Parties hereto, as expressed herein.
									Contact Us: If you have any questions about this Policy, the practices of the Platform, or your experience with the Service provided by the Platform, you can contact us at support@imayatech.in .
									</p>

								</div>
								
							</div>
						</div>
					</div>
				</section>
			</div>
		</div>
	</div>
<?php include("footer.php")?>
<script>
	window.onscroll = function() {myFunction()};

	var navbar = document.getElementById("navbar-section");
	var sticky = navbar.offsetTop;

	function myFunction() 
	{
		if (window.pageYOffset >= sticky) 
		{
			navbar.classList.add("sticky")
		}
		else 
		{
			navbar.classList.remove("sticky");
		}
	}
</script>
		